version: '3.8'

services:
  flask-app:
    build: ./flask_app
    container_name: flask-app-alt
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx-alt
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static-root:/usr/share/nginx/html:ro      
    depends_on:
      - flask-app
