version: '3.8'

services:
  django:
    build: ./django_app
    container_name: django-app
    volumes:
      - django_static:/app/static
    expose:
      - "8000"

  flask-app:
    build: ./flask_app
    container_name: flask-app-alt
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx-alt
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/static-root:/usr/share/nginx/html:ro
    depends_on:
      - flask-app
      - django

volumes:
  django_static: